name: default
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyter
  - black-jupyter
  - seaborn  # -> matplotlib, numpy, scipy, pandas
  - openpyxl
  - pingouin  # -> scikit-learn 
  - greenlet
  - salabim